chore: Update deploy workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,6 +41,11 @@ jobs:
           password: ${{ secrets.SERVER_PASSWORD }}
           port: 22
           script: |
+            if [ ! -f /etc/kbo-feed-service/feed.env ]; then
+              echo "[ERROR] Missing env file: /etc/kbo-feed-service/feed.env"
+              exit 1
+            fi
+
             echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
             cd ~/kbo-note/kbo-feed-service/deploy
             ./deploy.sh ${{ github.sha }}
